#!/bin/bash
EWW_BIN="~/.config/eww"
WIDGET=$1

# Open widgets
if ${EWW_BIN} windows | grep ^$WIDGET$ ; then
    ${EWW_BIN} close system audio_ctl calendar
    ${EWW_BIN} open "$WIDGET"
elif ${EWW_BIN} windows | grep ^\*$WIDGET$ ; then
    ${EWW_BIN} close "$WIDGET"
else exit
fi
